MSPF-579 Add prometheus metrics
rbkmoney/machinegun pull request #241
Opened 2020-10-27 07:48 UTC by ciiol

2020-10-27 07:57 UTC, kpy3 commented on rel_scripts/configurator.escript
> +        {prometheus          , prometheus (YamlConfig)},
+1 пробел?

2020-10-27 09:17 UTC, kpy3 requested changes

2020-10-27 09:23 UTC, ciiol commented on src/machinegun_pulse_prometheus.erl
> +        {help, "Machinegun timer processing durations."}
М, я добавил единицы изменения в название метрики (как это рекомедовано в https://prometheus.io/docs/practices/naming/). Думаешь, этого будет не достаточно?

2020-10-27 10:06 UTC, kpy3 commented on src/machinegun_pulse_prometheus.erl
> +        {help, "Machinegun timer processing durations."}
Возможно достаточно. Подсказана наверняка где-нибудь в попапе будет всплывать 🤔Но в целом не критично.

2020-10-27 10:16 UTC, ciiol commented on src/machinegun_pulse_prometheus.erl
> +        {help, "Machinegun timer processing durations."}
А в графане (если попап там будет) все равно единицы измерения явно указываются в параметрах графика.

2020-10-28 11:20 UTC, kpy3 approved these changes

2020-10-28 11:50 UTC, merged